AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloud Resume Challenge Backend Infrastructure

Resources:

  # 1. DynamoDB Table
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MyCRCresumeViewCount
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # 2. Lambda Function & API Gateway Trigger
  GetCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: resumefunc.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: MyCRCresumeViewCount
      FunctionUrlConfig:
        AuthType: NONE
        